---
title: "Pan-cancer improvements with mutations and MAPK scores"
author: "Michael Schubert (schubert@ebi.ac.uk)"
---

```{r code, include=FALSE}
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
st = import('stats')
df = import('data_frame')
plt = import('plot')
gdsc = import('data/gdsc')
util = import('./util')

INFILE = commandArgs(TRUE)[1] %or% "../../scores/gdsc/speed_matrix.RData"
OUTFILE = commandArgs(TRUE)[2] %or% "Pancan_assocs.pdf"

tissues = gdsc$tissues()
Ys = gdsc$drug_response('IC50s')
scores = io$load(INFILE)
mut = gdsc$mutated_genes(intogen=TRUE)
ar$intersect(tissues, Ys, scores, mut, along=1)

nst = function(x) names(x[x])
```

# Trametinib + MAPK

## Overview

```{r mapk, echo=FALSE}
mapk = scores[names(tissues), "MAPK"]
stratify = list(Pancan = list(
    "MAPK+" = nst(mapk > quantile(mapk)[4]), # top 25%
    "MAPK-" = nst(mapk < quantile(mapk)[2]), # bottom 25%
    "MAPK_null" = nst(mapk > quantile(mapk)[2] & mapk < quantile(mapk)[4]), # bottom 25%
    "MAPK_wt" = nst(!(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"])),
    "MAPK_mut" = nst(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"]),
    "MAPK+_mut" = nst((mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"]) & mapk > quantile(mapk)[4]),
    "MAPK-_mut" = nst((mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"]) & mapk < quantile(mapk)[4])
))

# could call this with any drug here (e.g. RDEA119, other drugs with strong assocs)
util$drug_range_box("Trametinib", stratify=stratify)
```

## Stratification by mutation alone

```{r mapk_1, echo=FALSE}
mapk = scores[names(tissues), "MAPK"]
stratify = list(Pancan = list(
    "MAPK_all" = nst(!is.na(mapk)),
    "MAPK_wt" = nst(!(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"])),
    "MAPK_mut" = nst(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"])
))

util$drug_range_box("Trametinib", stratify=stratify, plot_only=NULL)
util$drug_range_box("Trametinib", stratify=stratify)
```

## Stratification by pathway score alone

```{r mapk2, echo=FALSE}
mapk = scores[names(tissues), "MAPK"]
stratify = list(Pancan = list(
    "MAPK+" = nst(mapk > quantile(mapk)[4]), # top 25%
    "MAPK-" = nst(mapk < quantile(mapk)[2]), # bottom 25%
    "MAPK_null" = nst(mapk > quantile(mapk)[2] & mapk < quantile(mapk)[4]) # bottom 25%
))

util$drug_range_box("Trametinib", stratify=stratify, plot_only=NULL)
util$drug_range_box("Trametinib", stratify=stratify)
```

## Stratification of mutated/wild-type sub-population

```{r mapk3_1, echo=FALSE}
stratify = list(Pancan = list(
    "MAPK_wt" = nst(!(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"])),
    "MAPK+_wt" = nst((!(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"])) & mapk > quantile(mapk)[4]),
    "MAPK-_wt" = nst((!(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"])) & mapk < quantile(mapk)[2])
))

util$drug_range_box("Trametinib", stratify=stratify) + ggtitle("MAPK wt")
```

```{r mapk3, echo=FALSE}
stratify = list(Pancan = list(
    "MAPK_mut" = nst(mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"]),
    "MAPK+_mut" = nst((mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"]) & mapk > quantile(mapk)[4]),
    "MAPK-_mut" = nst((mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"]) & mapk < quantile(mapk)[4])
))

util$drug_range_box("Trametinib", stratify=stratify) + ggtitle("MAPK mut")
```

# RDEA119 + MAPK


# Nutlin-3a + p53


```{r p53, echo=FALSE}
p53 = scores[names(tissues), "p53"]
stratify = list(Pancan = list(
    "p53+" = nst(p53 > quantile(p53)[4]), # top 25%
    "p53-" = nst(p53 < quantile(p53)[2]), # bottom 25%
    "p53_null" = nst(p53 > quantile(p53)[2] & p53 < quantile(p53)[4]), # bottom 25%
    "TP53_wt" = nst(!mut[,"TP53"]),
    "TP53_mut" = nst(mut[,"TP53"]),
    "TP53+_mut" = nst(mut[,"TP53"] & p53 > quantile(p53)[3]),
    "TP53-_mut" = nst(mut[,"TP53"] & p53 < quantile(p53)[3])
))

util$drug_range_box("Nutlin-3a", stratify=stratify)
```
