---
title: "SKCM drug associations for perturbation-response genes"
author: "Michael Schubert (schubert@ebi.ac.uk)"
---

```{r code, include=FALSE}
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
st = import('stats')
df = import('data_frame')
plt = import('plot')
gdsc = import('data/gdsc')

INFILE = commandArgs(TRUE)[1] %or% "../../scores/gdsc/speed_matrix.RData"
OUTFILE = commandArgs(TRUE)[2] %or% "SCLC_assocs.pdf"

scores = io$load(INFILE)
tissues = gdsc$tissues("SCLC")
Yf = gdsc$drug_response('IC50s', min_tissue_measured=10)
ar$intersect(scores, tissues, Yf, along=1)
Yf = Yf[,ar$map(Yf, along=1, function(x) !all(is.na(x)))]

# tissues as subsets
assocs.tissue = st$lm(Yf ~ scores) %>%
    filter(term == "scores") %>%
    select(-term) %>%
    mutate(adj.p = p.adjust(p.value, method="fdr"))
```

```{r volcano, echo=FALSE}
assocs.tissue %>%
    mutate(label = paste(Yf, scores, sep=":")) %>%
    plt$color$p_effect(pvalue="adj.p", effect="estimate", dir=-1) %>%
    plt$volcano(p=0.2)
```

TNFa receptors are expressed in small fraction of cell lines,
NFkB1 expressed in most of them.

Best option should be to knock NFkB down/out + see how FK866
response changes in resistant cell lines.

```{r fits, echo=FALSE}
do_fit = function(tissue, drug, path, gene, label_top=5) {
    fits = df$assemble(
        drug = Yf[,drug],
        path = scores[,path],
        muts = gdsc$mutated_genes(intogen=TRUE, tissue=tissue) %>%
            ar$map(along=2, function(x) paste(names(x)[x], collapse=",")),
        gene = gdsc$basal_expression()[gene,]
#        gene = io$load('../../scores/gdsc/gsea_reactome.RData')[,'Trail']
    ) %>% na.omit()
    # <this should not be required once df$assemble works>
    fits$drug = as.numeric(fits$drug)
    fits$path = as.numeric(fits$path)
    fits$gene = as.numeric(fits$gene)
    # </>
    fits$label = gdsc$cosmic$id2name(rownames(fits))
    fits$label[fits$gene < b$maxN(fits$gene, 5)] = ""

    ggplot(fits, aes(x=path, y=drug, label=label, fill=gene)) +
        geom_smooth(method=stats::lm, se=FALSE, na.rm=TRUE, alpha=0.1) +
        geom_point(pch=21, size=5, colour="black", na.rm=TRUE) +
        scale_fill_gradient(low="white", high="black",
                            limits=c(min(fits$gene, na.rm=TRUE),
                                     max(fits$gene, na.rm=TRUE)),
                            guide = guide_legend(title = gene)) +
        geom_text(colour="#353535", size=2, vjust=-1.5, na.rm=TRUE) +
        theme_bw() +
        ggtitle(paste(tissue, ":", drug, "response and",
                      path, "activity")) +
        xlab(paste("predicted", path, "activity")) +
        ylab(paste("log IC50", drug))
}

print(do_fit("SCLC", "FK866", "TNFa", "TNFRSF1A"))
print(do_fit("SCLC", "FK866", "TNFa", "TNFRSF1B"))
print(do_fit("SCLC", "FK866", "TNFa", "NFKB1"))
print(do_fit("SCLC", "FK866", "TNFa", "NFKB2"))
```

```{r plk1, echo=FALSE}
print(do_fit("SCLC", "BI-2536", "TNFa", "PLK1"))
print(do_fit("SCLC", "BI-2536", "TNFa", "TNFRSF1A"))
print(do_fit("SCLC", "BI-2536", "TNFa", "NFKB1"))
```
