\section{Pan-cancer improvements with mutations and MAPK scores}

<<setup3, include=FALSE>>=
library(magrittr)
library(dplyr)
b = import('base')
io = import('io')
util = import('./util_3')
config = import('../config')

mapk_mut = c("NRAS", "KRAS", "BRAF")
@

\subsection{Improvement over mutations alone}

\begin{figure}[H]
<<tram, echo=FALSE, fig.height=3>>=
strat_tram = util$cmp_mut_path("MAPK", mapk_mut, "Trametinib", "mut")
util$plot_mut_path(strat_tram)
@
\caption{Trametinib}
\label{fig:strat-trametinib}
\end{figure}

\begin{figure}[H]
<<az628, echo=FALSE, fig.height=3>>=
strat_az628 = util$cmp_mut_path("MAPK", mapk_mut, "AZ628", "mut")
util$plot_mut_path(strat_az628)
@
\caption{AZ628}
\label{fig:strat-az628}
\end{figure}

\begin{figure}[H]
<<dabraf, echo=FALSE, fig.height=3>>=
strat_dabraf = util$cmp_mut_path("MAPK", "BRAF", "Dabrafenib", "mut")
util$plot_mut_path(strat_dabraf)
@
\caption{Dabrafenib}
\label{fig:strat-dabrafenib}
\end{figure}

\begin{figure}[H]
<<nutlin, echo=FALSE, fig.height=3>>=
strat_p53 = util$cmp_mut_path("p53", "TP53", "Nutlin-3a", "wt")
util$plot_mut_path(strat_p53)
@
\caption{Nutlin-3a}
\label{fig:strat-nutlin3a}
\end{figure}


\subsection{Comparing associations to mutations}

\begin{figure}[H]
<<compare, echo=FALSE>>=
resp = config$methods$ids %>%
    setdiff("paradigm") %>% # lowest FDR=39%
    c("mutation") %>% # compare mutations as well
    lapply(util$load_fun) %>%
    bind_rows()

ggplot(resp, aes(x=-log10(adj.p), y=log10(num), color=method)) +
    geom_step() +
    theme_bw()
@
\caption{Number and strength of associations}
\label{fig:strength-stepwise}
\end{figure}
