---
title: "Pan-cancer improvements with mutations and MAPK scores"
author: "Michael Schubert (schubert@ebi.ac.uk)"
---

```{r code, include=FALSE}
library(magrittr)
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
st = import('stats')
df = import('data_frame')
plt = import('plot')
gdsc = import('data/gdsc')
util = import('../analyses/drug_assocs_followup/util')

INFILE = commandArgs(TRUE)[1] %or% "../scores/gdsc/speed_matrix.RData"
OUTFILE = commandArgs(TRUE)[2] %or% "Pancan_assocs.pdf"

tissues = gdsc$tissues()
Ys = gdsc$drug_response('IC50s')
scores = io$load(INFILE)
mut = gdsc$mutated_genes(intogen=TRUE)
ar$intersect(tissues, Ys, scores, mut, along=1)

#' Generates a stratification structure using pathway and mutations
#'
#' @param pathway    Our pathway descriptor, e.g. "MAPK"
#' @param mutations  A character vector of which genes should be
#'                   used as markers to compare to
#' @param strat      For stratifications, look for subsets in "mut" or "wt"?
gen_subsets = function(pathway, mutations, strat="mut") {
    nst = function(x) names(x[x])

    # prepare stratifications of MAPK pathway
    path = scores[names(tissues), pathway]
    has_mut = apply(mut[,mutations, drop=FALSE], 1, any)
    path_active = path > quantile(path)[4] # top 25%
    path_inactive = path < quantile(path)[2] # bottom 25%
    path_null = path > quantile(path)[2] & path < quantile(path)[4] # rest

    re = list(
        # stratification by mutation
        "all" = nst(!is.na(path)),
        "wt" = nst(!has_mut),
        "mut" = nst(has_mut)
    )

    if (strat == "wt") {
        # stratification by SPEED score
        re[["path+"]] = nst(path_active)
        re[["path-"]] = nst(path_inactive | path_null)

        # stratification by SPEED score, wild-type subset
        re[["path+_wt"]] = nst(!has_mut & (path_active | path_null))
        re[["path-_wt"]] = nst(!has_mut & path_inactive)
    } else if (strat == "mut") {
        # stratification by SPEED score
        re[["path+"]] = nst(path_active)
        re[["path-"]] = nst(path_inactive | path_null)

        # stratification by SPEED score, mutated subset
        re[["path+_mut"]] = nst(has_mut & path_active)
        re[["path-_mut"]] = nst(has_mut & (path_inactive | path_null))
    }

    re
}

assemble_df = function(subs, drug) {
    mydf = stack(subs)
    mydf$tissue = gdsc$tissues()[mydf$values]
    mydf$resp = gdsc$drug_response()[,drug][mydf$values]
    mydf
}

summary_df = function(mydf) {
    mydf %>%
        group_by(ind) %>%
        summarize(n = n()) %$%
        setNames(n, ind) %>%
        print()

    # depending on whether we select wt or mut to be stratified, this will
    # do the test for that pair (=the one that is present in the data.frame)

    # do a mann-whitny u test for difference within already stratified pop
    # and report the p-value
    mydf %>%
        filter(ind %in% c("path+_wt", "path-_wt", "path+_mut", "path-_mut")) %>%
        wilcox.test(resp ~ ind, data=.) %$%
        message(paste("p-value wilcox:" , as.character(p.value)))

    # also report the ratio of medians, because the W statistic is hard
    # to interpret
    mydf %>%
        filter(ind %in% c("path+_wt", "path-_wt", "path+_mut", "path-_mut")) %>%
        group_by(ind) %>%
        summarize(median = median(resp)) %$%
        message(paste("median difference (fold):", 10^(median[2] - median[1])))
}

MEKi_MAPK = gen_subsets("MAPK", c("NRAS", "KRAS", "BRAF"))
BRAFi_MAPK = gen_subsets("MAPK", "BRAF")
Nutlin_p53 = gen_subsets("p53", "TP53", strat="wt")
```

# Improvement over mutations alone

#### Trametinib

```{r tram, echo=FALSE, fig.height=3}
#mut = gdsc$mutated_genes()[,c("KRAS","NRAS","BRAF")]
#mydf$mut = ar$map(mut, along=2, function(x) colnames(mut)[x][1])[mydf$values]
#mydf$mut[is.na(mydf$mut)] = "wt"
#TODO: the above drops a 2nd mut if avail (same below)
mydf = assemble_df(MEKi_MAPK, "Trametinib") %>% na.omit()
mydf$ind = factor(mydf$ind, levels=c("all", "wt", "mut",
                                     "path+_mut", "path-_mut",
                                     "path+", "path0", "path-"))
summary_df(mydf)

ggplot(mydf, aes(x=ind, y=resp)) +
    geom_violin() +
    geom_boxplot(width=.5, outlier.shape=NA) +
#    geom_boxplot(outlier.shape=NA) +
#    geom_point(aes(colour=tissue, shape=mut), size=5, alpha=0.5, position=position_jitter(w=0.5))
    theme_bw()
```

#### AZ628

```{r az628, echo=FALSE, fig.height=3}
mydf = assemble_df(MEKi_MAPK, "AZ628") %>% na.omit()
mydf$ind = factor(mydf$ind, levels=c("all", "wt", "mut",
                                     "path+_mut", "path-_mut",
                                     "path+", "path0", "path-"))
summary_df(mydf)

ggplot(mydf, aes(x=ind, y=resp)) +
    geom_violin() +
    geom_boxplot(width=.5, outlier.shape=NA) +
    theme_bw()
```

#### Dabrafenib

```{r dabraf, echo=FALSE, fig.height=3}
mydf = assemble_df(BRAFi_MAPK, "Dabrafenib") %>% na.omit()
mydf$ind = factor(mydf$ind, levels=c("all", "wt", "mut",
                                     "path+_mut", "path-_mut",
                                     "path+", "path0", "path-"))
summary_df(mydf)

ggplot(mydf, aes(x=ind, y=resp)) +
    geom_violin() +
    geom_boxplot(width=.5, outlier.shape=NA) +
    theme_bw()
```

#### Nutlin-3a

```{r vx, echo=FALSE, fig.height=3}
mydf = assemble_df(Nutlin_p53, "Nutlin-3a") %>% na.omit()
mydf$ind = factor(mydf$ind, levels=c("all", "mut", "wt",
                                     "path+_wt", "path-_wt",
                                     "path+", "path0", "path-"))
summary_df(mydf)

ggplot(mydf, aes(x=ind, y=resp)) +
    geom_violin() +
    geom_boxplot(width=.5, outlier.shape=NA) +
    theme_bw()
```


# Comparing associations to mutations

```{r compare, echo=FALSE}
load_fun = function(fname) {
    io$file_path('../analyses/drug_assocs', fname, ext=".RData") %>%
        io$load() %$%
        assocs.pan %>%
        filter(adj.p < 0.1) %>%
        arrange(adj.p) %>%
        mutate(num = 1:nrow(.),
               method = fname)
}

# paradigm not included because strongest pancan association 39% FDR
methods = c("mutation", "speed_matrix", "gsea_reactome", "gsea_go", "spia", "pathifier")

resp = methods %>%
    lapply(load_fun) %>%
    bind_rows()

ggplot(resp, aes(x=-log10(adj.p), y=log10(num), color=method)) +
    geom_step() +
    theme_bw()
```
