---
title: "Associations between pathway activation and patient survival"
author: "Michael Schubert (schubert@ebi.ac.uk)"
---

```{r setup, include=FALSE}
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
df = import('data_frame')
st = import('stats')
plt = import('plot')
tcga = import('data/tcga')
surv = import('../analyses/tcga_survival/util')

scores = c('gsea_reactome', 'gsea_go', 'speed_matrix', 'pathifier', 'spia') %>%
    sapply(surv$load, simplify=FALSE, USE.NAMES=TRUE)

assocs.pan = scores %>%
    sapply(surv$pancan, simplify=FALSE, USE.NAMES=FALSE) %>%
    df$add_name_col("method") %>%
    bind_rows()

assocs.tissue = surv$tissue(scores$speed_matrix)

clinical = surv$clinical
scores = scores$speed_matrix
ar$intersect(scores, clinical$barcode, along=1)
discrete_scores = ar$map(scores, along=1, subsets=clinical$study, surv$discretize_quartiles)
discrete_assocs = surv$tissue(discrete_scores)
```

# Pan-cancer associations

```{r pancan, include=FALSE}
##TODO: @suppl
#assocs.pan %>%
#    plt$color$p_effect("adj.p", dir=-1) %>%
#    mutate(label = scores) %>%
#    plt$volcano(base.size=0.1) %>%
#    print()
```

```{r heatmap, echo=FALSE, fig.height=3}
lmax = max(abs(assocs.pan$statistic), na.rm=TRUE)
p1 = assocs.pan %>%
    mutate(statistic = ifelse(adj.p < 0.2, statistic, NA)) %>%
    mutate(label = ifelse(adj.p < 0.05, "*", "")) %>%
    mutate(label = ifelse(adj.p < 1e-5, "**", label)) %>%
    mutate(label = ifelse(adj.p < 1e-10, "***", label)) %>%
    plt$matrix(statistic ~ method + scores, color="statistic", limits=c(-lmax,lmax))
print(p1)
```

# Cancer-specific associations

```{r tissue, echo=FALSE}
##TODO: for all other methods ->@suppl
p2 = assocs.tissue %>%
    plt$color$p_effect("adj.p", dir=-1, thresh=0.1) %>%
    mutate(label = paste(subset, scores, sep=":")) %>%
    plt$volcano(p=0.1, base.size=0.1)
print(p2)
```

# Highlighted fits

```{r fit1, echo=FALSE, fig.width=7.5, fig.height=6}
scores = discrete_scores
surv$row2survFit(unlist(filter(discrete_assocs, scores=="TNFa" & subset=="KIRC")))
```
