<<setup_drug_over_mut, include=FALSE>>=
library(magrittr)
library(dplyr)
b = import('base')
io = import('io')
df = import('data_frame')
util = import('./util_3')
config = import('../config')

mapk_mut = c("NRAS", "KRAS", "BRAF")

strats = list(
    `MAPK + Trametinib` = util$cmp_mut_path("MAPK", mapk_mut, "Trametinib", "mut"),
    `MAPK + AZ628` = util$cmp_mut_path("MAPK", mapk_mut, "AZ628", "mut"),
    `BRAF + Dabrafenib` = util$cmp_mut_path("MAPK", "BRAF", "Dabrafenib", "mut"),
    `p53 + Nutlin-3a` = util$cmp_mut_path("p53", "TP53", "Nutlin-3a", "wt")
)
@

\begin{figure}[H]
<<tram, echo=FALSE, fig.height=3>>=
util$plot_mut_path(strats[[1]])
@
\caption{Trametinib}
\label{fig:strat-trametinib}
\end{figure}

\begin{figure}[H]
<<az628, echo=FALSE, fig.height=3>>=
util$plot_mut_path(strats[[2]])
@
\caption{AZ628}
\label{fig:strat-az628}
\end{figure}

\begin{figure}[H]
<<dabraf, echo=FALSE, fig.height=3>>=
util$plot_mut_path(strats[[3]])
@
\caption{Dabrafenib}
\label{fig:strat-dabrafenib}
\end{figure}

\begin{figure}[H]
<<nutlin, echo=FALSE, fig.height=3>>=
util$plot_mut_path(strats[[4]])
@
\caption{Nutlin-3a}
\label{fig:strat-nutlin3a}
\end{figure}
