<<setup_drug_over_mut_stats, include=FALSE>>=
library(magrittr)
library(dplyr)
b = import('base')
io = import('io')
df = import('data_frame')
util = import('./util_3')
config = import('../config')

mapk_mut = c("NRAS", "KRAS", "BRAF")

strats = list(
    `MAPK + Trametinib` = util$cmp_mut_path("MAPK", mapk_mut, "Trametinib", "mut"),
    `MAPK + AZ628` = util$cmp_mut_path("MAPK", mapk_mut, "AZ628", "mut"),
    `BRAF + Dabrafenib` = util$cmp_mut_path("MAPK", "BRAF", "Dabrafenib", "mut")
#    `p53 + Nutlin-3a` = util$cmp_mut_path("p53", "TP53", "Nutlin-3a", "wt")
)
@

\begin{table}[H]
\centering
\caption{Stratification statistics: subsets and numbers for figure 4c. Shown is
    the combination between a mutation/pathway, the number of cell lines, and
        median drug response in each subset. Subsets are defined by: (1)
        Whether a mutation is present (mut) or not (wt), or disregarding
        mutational status (blank). (2) Whether the pathway score is in the top
        (active) or bottom quartile (inactive), or neither (blank) of the
        subset defined by mutations.}
{\small
<<strat_table, echo=FALSE, warning=FALSE>>=
path_lookup = setNames(c("active", "inactive", "average"), c("+", "-", "0"))
tab = df$add_name_col(strats, "treatment", bind=TRUE) %>%
    group_by(treatment, subset) %>%
    summarize(n = n_distinct(cosmic),
              median = median(resp, na.rm=TRUE)) %>%
    ungroup() %>%
    transmute(Treatment = treatment,
              Mutation = b$grep("_(mut|wt)", subset),
              Pathway = path_lookup[b$grep("([+-0])", subset)],
              `Number of cell lines` = n,
              `Median DR [log uM]` = median)

tab[is.na(tab)] = " "
arrange(tab, Treatment, Mutation, Pathway) %>%
    kable(digits=2, booktabs=TRUE)
@
}
\end{table}

\begin{table}[H]
\centering
\caption{Stratification statistics: significance tests for figure 4c. For the
    same subsets, results of the Mann-Whitney U test between different
        quartiles of the pathway score within different subsets defined by
        mutational status with p-value as indicated. Difference in mutations
        indicated by wt (wild-type), mut (mutated), or blank (any). Inferred
        pathway activity is indicated by $+$ (top quartile) $-$ (bottom
        quartile) or blank (any). Distance reported as a fold change of medians.}
{\small
<<strat_table_test, echo=FALSE>>=
b$lnapply(strats, util$contrast_stats) %>%
    df$add_name_col("treatment", bind=TRUE) %>%
    transmute(Treatment = treatment,
              Reference = ref,
              Comparison = sample,
              `p-value` = format(p.value, digits=3),
              `FC (medians)` = median_folds) %>%
    kable(digits=50, booktabs=TRUE)
@
}
\end{table}
