\documentclass{article}

\input{config}

\title{Generated Figures}
\author{Michael Schubert (schubert@ebi.ac.uk)}

\begin{document}

\maketitle

\tableofcontents

\Sexpr{knit_child('global_expr.Rnw')}

\Sexpr{knit_child('mut_cna_methods.Rnw')}

\Sexpr{knit_child('drug_assoc_steps.Rnw')}

\Sexpr{knit_child('drug_over_mut.Rnw')}

\Sexpr{knit_child('survival_pancan.Rnw')}

\Sexpr{knit_child('survival_fits.Rnw')}

\end{document}
