\subsection{Image sources for Fig. 1b}

Images published under Creative Commons BY-SA\footnotemark[1] have been reused
as parts of the workflow in Fig. 1b, for the microarray schema\footnotemark[2],
   the z-score distribution\footnotemark[3], and matrix
   multiplication\footnotemark[4]. \\
\\ 
\footnotemark[1] \url{https://creativecommons.org/licenses/} \\
\footnotemark[2] \url{https://commons.wikimedia.org/wiki/File:DNA\_microarray.svg} \\
\footnotemark[3] \url{https://commons.wikimedia.org/wiki/File:Boxplot\_vs\_PDF.svg} \\
\footnotemark[4] \url{https://commons.wikimedia.org/wiki/File:Matrix\_multiplication\_diagram\_2.svg}
