%\subsection{Gene sets used for different pathway methods}

%TODO: generate from config [need to fix list levels first]
%\begin{table}[H]
%\centering
%\caption{Pathway mapping for Gene Ontology}
%<<path_go, echo=FALSE>>=
%kable(roc$auc, digits=2, booktabs=TRUE)
%@
%\end{table}


\begin{table}[H]
\centering
\caption{Pathway mapping for Gene Ontology}
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{Gene Ontology}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & GO:0007259 & ERBB signaling pathway\tabularnewline
Hypoxia & GO:0071456 & cellular response to hypoxia\tabularnewline
JAK-STAT & GO:0007259 & JAK-STAT signal transduction\tabularnewline
MAPK & GO:0000165 & MAPK cascade\tabularnewline
NFkB & GO:0038061 & NIK/NF-kappaB signaling\tabularnewline
p53 & GO:0030330 & DNA damage response, signal transduction by p53 class mediator\tabularnewline
PI3K & GO:0014065 & phosphatidylinositol 3-kinase signaling\tabularnewline
TNFa & GO:0033209 & tumor necrosis factor-mediated signaling pathway\tabularnewline
TGFb & GO:0007179 & transforming growth factor beta receptor signaling pathway\tabularnewline
Trail & GO:0036462 & TRAIL-activated apoptotic signaling pathway\tabularnewline
VEGF & GO:0038084 & vascular endothelial growth factor signaling pathway\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for Reactome and Pathifier}
\begin{tabular}{cc}
\hline
\multirow{1}{*}{Pathway} & Name\tabularnewline
\hline
\multirow{2}{*}{EGFR} & Signaling by EGFR\tabularnewline
 & Signaling by EGFR in Cancer\tabularnewline
Hypoxia & Cellular response to hypoxia\tabularnewline
\multirow{3}{*}{JAK-STAT} & Signaling by Interleukins\tabularnewline
 & Interferon Signaling\tabularnewline
 & Signalling to STAT3\tabularnewline
MAPK & Signalling to ERKs\tabularnewline
\multirow{2}{*}{NFkB} & TAK1 activates NFkB:w: by phosphorylation and activation of IKKs complex\tabularnewline
 & RIP-mediated NFkB activation via ZBP1\tabularnewline
p53 & Transcriptional Regulation by TP53\tabularnewline
\multirow{4}{*}{PI3K} & PI3K Cascade\tabularnewline
 & Constitutive Signaling by Aberrant PI3K in Cancer\tabularnewline
 & PI3K/AKT Signaling in Cancer\tabularnewline
 & PI3K/AKT activation\tabularnewline
TNFa & TNF signaling\tabularnewline
TGFb & Signaling by TGF-beta Receptor Complex\tabularnewline
Trail & TRAIL signaling\tabularnewline
VEGF & Signaling by VEGF\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for SPIA}
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{SPIA}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & 04012 & ErbB signaling pathway\tabularnewline
Hypoxia & - & -\tabularnewline
JAK-STAT & 04630 & Jak-STAT signaling pathway\tabularnewline
MAPK & 04010 & MAPK signaling pathway\tabularnewline
NFkB & 04064 & NF-kappa B signaling pathway\tabularnewline
p53 & - & -\tabularnewline
PI3K & 04150 & mTOR signaling pathway\tabularnewline
TNFa & - & -\tabularnewline
TGFb & 04350 & TGF-beta signaling pathway\tabularnewline
Trail & 04210 & Apoptosis\tabularnewline
VEGF & 04370 & VEGF signaling pathway\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for PARADIGM}
\begin{tabular}{cc}
\hline
\multirow{2}{*}{Pathway} & \multirow{2}{*}{PARADIGM}\tabularnewline
 & \tabularnewline
\hline
EGFR & epidermal growth factor receptor activity (abstract)\tabularnewline
Hypoxia & response to hypoxia (abstract)\tabularnewline
JAK-STAT & STAT-1-3-5-active\tabularnewline
\multirow{1}{*}{MAPK} & MEK-1-2-active\tabularnewline
NFkB & NFkB Complex (complex)\tabularnewline
p53 & response to DNA damage stimulus (abstract)\tabularnewline
PI3K & PIK3CA\tabularnewline
TNFa & tumor necrosis factor receptor activity (abstract)\tabularnewline
TGFb & SMAD1-5-8-active\tabularnewline
Trail & induction of apoptosis (abstract)\tabularnewline
VEGF & platelet-derived growth factor receptor activity (abstract)\tabularnewline
\hline
\end{tabular}
\end{table}
