%\subsection{Gene sets used for different pathway methods}

%TODO: generate from config [need to fix list levels first]
%\begin{table}[H]
%\centering
%\caption{Pathway mapping for Gene Ontology}
%<<path_go, echo=FALSE>>=
%kable(roc$auc, digits=2, booktabs=TRUE)
%@
%\end{table}

\begin{table}[H]
\caption{Pathway mapping for different methods}
\centering

\subfloat[Gene Ontology. GO categories (ID and name) shown
    for the 11 pathways we investigate.]{
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{Gene Ontology}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & GO:0007259 & ERBB signaling pathway\tabularnewline
Hypoxia & GO:0071456 & cellular response to hypoxia\tabularnewline
JAK-STAT & GO:0007259 & JAK-STAT signal transduction\tabularnewline
MAPK & GO:0000165 & MAPK cascade\tabularnewline
NFkB & GO:0038061 & NIK/NF-kappaB signaling\tabularnewline
p53 & GO:0030330 & DNA damage response, signal transduction by p53 class mediator\tabularnewline
PI3K & GO:0014065 & phosphatidylinositol 3-kinase signaling\tabularnewline
TNFa & GO:0033209 & tumor necrosis factor-mediated signaling pathway\tabularnewline
TGFb & GO:0007179 & transforming growth factor beta receptor signaling pathway\tabularnewline
Trail & GO:0036462 & TRAIL-activated apoptotic signaling pathway\tabularnewline
VEGF & GO:0038084 & vascular endothelial growth factor signaling pathway\tabularnewline
\hline
\end{tabular}
}

\subfloat[Reactome and Pathifier. Listed are reactome
    pathway names that were used either for GSVA pathway scores or Pathifier
        scores using the respective R packages. If more than one pathway is
        listed all of them were used in the gene set.]{
\begin{tabular}{cc}
\hline
Pathway & Name\tabularnewline
\hline
\multirow{2}{*}{EGFR} & Signaling by EGFR\tabularnewline
 & Signaling by EGFR in Cancer\tabularnewline
Hypoxia & Cellular response to hypoxia\tabularnewline
\multirow{3}{*}{JAK-STAT} & Signaling by Interleukins\tabularnewline
 & Interferon Signaling\tabularnewline
 & Signalling to STAT3\tabularnewline
MAPK & Signalling to ERKs\tabularnewline
\multirow{2}{*}{NFkB} & TAK1 activates NFkB:w: by phosphorylation and activation of IKKs complex\tabularnewline
 & RIP-mediated NFkB activation via ZBP1\tabularnewline
p53 & Transcriptional Regulation by TP53\tabularnewline
\multirow{4}{*}{PI3K} & PI3K Cascade\tabularnewline
 & Constitutive Signaling by Aberrant PI3K in Cancer\tabularnewline
 & PI3K/AKT Signaling in Cancer\tabularnewline
 & PI3K/AKT activation\tabularnewline
TNFa & TNF signaling\tabularnewline
TGFb & Signaling by TGF-beta Receptor Complex\tabularnewline
Trail & TRAIL signaling\tabularnewline
VEGF & Signaling by VEGF\tabularnewline
\hline
\end{tabular}
}

\subfloat[Signaling Pathway Impact Analysis. KEGG pathway IDs and names that SPIA relies
on are listed (this is part of the SPIA R package).]{
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{SPIA}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & 04012 & ErbB signaling pathway\tabularnewline
Hypoxia & - & -\tabularnewline
JAK-STAT & 04630 & Jak-STAT signaling pathway\tabularnewline
MAPK & 04010 & MAPK signaling pathway\tabularnewline
NFkB & 04064 & NF-kappa B signaling pathway\tabularnewline
p53 & - & -\tabularnewline
PI3K & 04150 & mTOR signaling pathway\tabularnewline
TNFa & - & -\tabularnewline
TGFb & 04350 & TGF-beta signaling pathway\tabularnewline
Trail & 04210 & Apoptosis\tabularnewline
VEGF & 04370 & VEGF signaling pathway\tabularnewline
\hline
\end{tabular}
}

\phantomcaption
\end{table}
\begin{table}[!htbp]
\ContinuedFloat
\centering

\subfloat[PARADIGM. This method is different as it performs
inference on a signaling network instead of providing pathways itself. We used
the network the TCGA is using in their
analyses\footnote{https://tcga-data.nci.nih.gov/docs/publications/coadread_2012/}.
This network has activity nodes for pathways and important processes that we
used here, as listed.]{
\begin{tabular}{cc}
\hline
Pathway & PARADIGM\tabularnewline
\hline
EGFR & epidermal growth factor receptor activity (abstract)\tabularnewline
Hypoxia & response to hypoxia (abstract)\tabularnewline
JAK-STAT & STAT-1-3-5-active\tabularnewline
MAPK & MEK-1-2-active\tabularnewline
NFkB & NFkB Complex (complex)\tabularnewline
p53 & response to DNA damage stimulus (abstract)\tabularnewline
PI3K & PIK3CA\tabularnewline
TNFa & tumor necrosis factor receptor activity (abstract)\tabularnewline
TGFb & SMAD1-5-8-active\tabularnewline
Trail & induction of apoptosis (abstract)\tabularnewline
VEGF & platelet-derived growth factor receptor activity (abstract)\tabularnewline
\hline
\end{tabular}
}

\subfloat[Signatures published and validated in Gatza et al. (2009)]{
\begin{tabular}{cc}
\hline
Pathway & Gatza (2009)\tabularnewline
\hline
EGFR & EGFR\tabularnewline
Hypoxia & HYPOXIA\tabularnewline
JAK-STAT & STAT1, STAT3, IFNA, IFNG\tabularnewline
MAPK & PROLIFERATION, PROLIFERATION (PAM50)\tabularnewline
p53 & P53, P53 MUT/P53 WT CORR\tabularnewline
PI3K & PI3K, PIK3CA\tabularnewline
TNFa & TNFA\tabularnewline
TGFb & TGFB\tabularnewline
VEGF & VEGF/HYPOXIA\tabularnewline
\hline
\end{tabular}
}

\end{table}
