<<setup_roc, include=FALSE>>=
library(dplyr)
roc = import('../analyses/perturbation_recall/roc')
config = import('../config')
@

\begin{figure}[H]
<<roc_curves, echo=FALSE>>=
roc$roc %>%
    mutate(method = config$id2short(method)) %>%
    roc$do_plot(width=1.05) +
        config$facet_theme +
        xlab("False positive rate (FPR)") +
        ylab("True positive rate (FPR)")
@
\caption{ROC curves for different pathway methods}
\label{fig:roc}
\end{figure}
