<<setup_roc_auc, include=FALSE>>=
library(dplyr)
roc = import('../analyses/perturbation_recall/roc')

auc = roc$analysis_set2roc() %>%
	roc$roc2auc()
@

\begin{table}[H]
\centering
\caption{Area under the ROC curve for perturbation experiments. Pathway
    scores derived by different pathway methods, known pathway perturbations
        are True Positives. }
<<roc_auc, echo=FALSE>>=
kable(auc, digits=2, booktabs=TRUE)
@
\end{table}
