\section{Pathway scores in Basal and Perturbed Condition}

<<setup1, include=FALSE>>=
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
st = import('stats')
plt = import('plot')
util = import('./util_1')
config = import('../config')
@

\subsection{Size of the data set}

\begin{figure}[H]
<<dataset_size, echo=FALSE>>=
bars = import('../analyses/speed_overview/plot_bars')
bars$create_df() %>%
    mutate(variable = config$id2short(variable)) %>%
    bars$do_plot()
@
\caption{Comparison of dataset size between SPEED, Gatza2014, and ours}
\label{fig:dataset_size}
\end{figure}


%\subsection{Global Structure of perturbation experiments}
%
%\begin{figure}[H]
%<<global_structure, echo=FALSE, fig.width=10>>=
%import('../analyses/speed_raw/plot')$do_plot()
%@
%\caption{Clustering of fold changes (left) and top 100 genes (right)}
%\label{fig:clust}
%\end{figure}


\subsection{Statistical significance of signature genes}

\begin{table}[H]
\centering
\caption{Significance of the top 100 signature genes}
<<sig_sign, echo=FALSE>>=
kable(import('../analyses/speed_overview/model_significance')$summary(),
      digits=30, booktabs=TRUE)
@
\end{table}


\subsection{Gene sets used for different pathway methods}

%TODO: generate from config [need to fix list levels first]
%\begin{table}[H]
%\centering
%\caption{Pathway mapping for Gene Ontology}
%<<path_go, echo=FALSE>>=
%kable(roc$auc, digits=2, booktabs=TRUE)
%@
%\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for Gene Ontology}
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{Gene Ontology}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & GO:0007259 & ERBB signaling pathway\tabularnewline
Hypoxia & GO:0071456 & cellular response to hypoxia\tabularnewline
JAK-STAT & GO:0007259 & JAK-STAT signal transduction\tabularnewline
MAPK & GO:0000165 & MAPK cascade\tabularnewline
NFkB & GO:0038061 & NIK/NF-kappaB signaling\tabularnewline
p53 & GO:0030330 & DNA damage response, signal transduction by p53 class mediator\tabularnewline
PI3K & GO:0014065 & phosphatidylinositol 3-kinase signaling\tabularnewline
TNFa & GO:0033209 & tumor necrosis factor-mediated signaling pathway\tabularnewline
TGFb & GO:0007179 & transforming growth factor beta receptor signaling pathway\tabularnewline
Trail & GO:0036462 & TRAIL-activated apoptotic signaling pathway\tabularnewline
VEGF & GO:0038084 & vascular endothelial growth factor signaling pathway\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for Reactome and Pathifier}
\begin{tabular}{cc}
\hline
\multirow{1}{*}{Pathway} & Name\tabularnewline
\hline
\multirow{2}{*}{EGFR} & Signaling by EGFR\tabularnewline
 & Signaling by EGFR in Cancer\tabularnewline
Hypoxia & Cellular response to hypoxia\tabularnewline
\multirow{3}{*}{JAK-STAT} & Signaling by Interleukins\tabularnewline
 & Interferon Signaling\tabularnewline
 & Signalling to STAT3\tabularnewline
MAPK & Signalling to ERKs\tabularnewline
\multirow{2}{*}{NFkB} & TAK1 activates NFkB:w: by phosphorylation and activation of IKKs complex\tabularnewline
 & RIP-mediated NFkB activation via ZBP1\tabularnewline
p53 & Transcriptional Regulation by TP53\tabularnewline
\multirow{4}{*}{PI3K} & PI3K Cascade\tabularnewline
 & Constitutive Signaling by Aberrant PI3K in Cancer\tabularnewline
 & PI3K/AKT Signaling in Cancer\tabularnewline
 & PI3K/AKT activation\tabularnewline
TNFa & TNF signaling\tabularnewline
TGFb & Signaling by TGF-beta Receptor Complex\tabularnewline
Trail & TRAIL signaling\tabularnewline
VEGF & Signaling by VEGF\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for SPIA}
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{SPIA}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & 04012 & ErbB signaling pathway\tabularnewline
Hypoxia & - & -\tabularnewline
JAK-STAT & 04630 & Jak-STAT signaling pathway\tabularnewline
MAPK & 04010 & MAPK signaling pathway\tabularnewline
NFkB & 04064 & NF-kappa B signaling pathway\tabularnewline
p53 & - & -\tabularnewline
PI3K & 04150 & mTOR signaling pathway\tabularnewline
TNFa & - & -\tabularnewline
TGFb & 04350 & TGF-beta signaling pathway\tabularnewline
Trail & 04210 & Apoptosis\tabularnewline
VEGF & 04370 & VEGF signaling pathway\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for PARADIGM}
\begin{tabular}{cc}
\hline
\multirow{2}{*}{Pathway} & \multirow{2}{*}{PARADIGM}\tabularnewline
 & \tabularnewline
\hline
EGFR & epidermal growth factor receptor activity (abstract)\tabularnewline
Hypoxia & response to hypoxia (abstract)\tabularnewline
JAK-STAT & STAT-1-3-5-active\tabularnewline
\multirow{1}{*}{MAPK} & MEK-1-2-active\tabularnewline
NFkB & NFkB Complex (complex)\tabularnewline
p53 & response to DNA damage stimulus (abstract)\tabularnewline
PI3K & PIK3CA\tabularnewline
TNFa & tumor necrosis factor receptor activity (abstract)\tabularnewline
TGFb & SMAD1-5-8-active\tabularnewline
Trail & induction of apoptosis (abstract)\tabularnewline
VEGF & platelet-derived growth factor receptor activity (abstract)\tabularnewline
\hline
\end{tabular}
\end{table}


\begin{figure}[H]
<<genesets, echo=FALSE, fig.width=19, fig.height=15>>=
import('../analyses/speed_overview/geneset_overlap')$venn()
@
\caption{Difference in gene sets between Perturbation-response genes and Gene Ontology/Reactome}
\label{fig:genesets}
\end{figure}

\subsection{Pathway scores of different methods assigned to perturbations}

Below are comparisons of the associations between input experiments and a
higher pathway score (left), as well as the scores assigned to each individual
perturbation experiment in our database (right).

We calculate linear associations using the *lm* function in R between a
pathway coefficients matrix (of the shape experiments x pathways, with the
value 1 where a pathway was activated, -1 where a pathway was
inhibited, and 0 otherwise; here, no cross-talk was modelled
explicitly) and the pathway scores obtained by using the different
methods. We then plot the result of the associations as a
heatmap where the perturbed pathway and the obtained pathway score are on the
axes, and the colour (blue for positive and red for negative correlation)
indicates the Wald statistic between them. We annotate combinations where
the p-value is below $10^{-5}$ with `*` and where it is $10^{-10}$ with $***$.

As a method for inspection of the pathway scores of the individual
experiments, We plot a heatmap using the R package *pheatmap*
with the pathways scores in rows, experiments in columns, and the
colour indicates the relative activation (scores scaled within experiments
across pathways) of each
pathway. In order to make activations and inhibitions more
comparable, we take the negative pathway score for each inhibition
and annotate the columns separately indicating which pathway was
perturbed, and which kind of perturbation it was and we ordered the pathway in
the following order: EGFR, H2O2, Hypoxia, JAK-STAT, MAPK, NFkB, PI3K,
TGFb, TNFa, Trail, VEGF, p53).

\begin{figure}[H]
\subfloat[Perturbation-response genes]{
<<perturb_speed, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('speed_matrix')
@
}

\subfloat[Gene Ontology]{
<<perturb_go, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('gsva_go')
@
}
\end{figure}
\begin{figure}[H]
\ContinuedFloat

\subfloat[Reactome]{
<<perturb_reactome, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('gsva_reactome')
@
}

\subfloat[BioCarta]{
<<perturb_biocarta, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('gsva_biocarta')
@
}

\subfloat[SPIA]{
<<perturb_spia, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('spia')
@
}

\subfloat[Pathifier]{
<<perturb_pathifier, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('pathifier')
@
}

%\subfloat[PARADIGM]{
%<<perturb_paradigm, echo=FALSE, fig.width=8, fig.height=3>>=
%util$perturb_score_plots('paradigm')
%@
%}
\caption{Pathway methods}
\label{fig:perturb_simple}
\end{figure}


\subsection{Consensus signature corresponds more closely to perturbations than pathway methods}

%TODO: consensus not perfect, GEX sig confounded, will not be 100\% with simple model (only when overfitted)

While the previous section focussed on pathway activation in relative terms
(whether, given a pathway perturbation, the score assigned to any one pathway
is higher or lower compared to other pathways), I am now interested in how well
pathway methods are able to assign activity scores across different
experiments. I use as input data the fold changes (difference in log space, or
negative difference if inhibition) of the curated perturbation experiments, and
see how well the pathway scores derived from those are ordered for each pathway
across experiments. This is meant as a comparison how well the pathway scores
obtained by different methods correspond to perturbations, and not to assign
significance of the perturbation-response signature model. Because then I would
need an independent set of experiments. This is not required as I assessed the
significance of this model analytically, with results shown in table
tab:Significance-of-signature. The comparison here serves to show that my
model corresponds better to perturbations.

%\begin{figure}[H]
%<<roc_curves, echo=FALSE>>=
%roc = import('../analyses/speed_raw/roc')
%roc$roc %>%
%    mutate(method = config$id2short(method)) %>%
%    roc$do_plot(width=1.05) +
%        config$facet_theme +
%        xlab("False positive rate (FPR)") +
%        ylab("True positive rate (FPR)")
%@
%\caption{ROC curves for different pathway methods}
%\label{fig:roc}
%\end{figure}

\begin{table}[H]
\centering
\caption{AUC under the ROC curve}
<<roc_auc, echo=FALSE>>=
roc = import('../analyses/speed_raw/roc')
kable(roc$auc, digits=2, booktabs=TRUE)
@
\end{table}


The standard non-parametric (i.e., only based on order rather than value) of
quantifying this are Receiver-Operator (ROC) curves, the results of which are
shown in figure *** (AUCs in table ***. For all pathways
except NFkB and JAK-STAT (where multiple methods are tied), the consensus gene
signature I derived is also better able to detect pathway activations across
experiments. VEGF is not well recovered by any method, potentially due to the
relatedness with EGFR/MAPK and the low number of experiments. Interestingly,
SPIA in 4 out of 11 cases systematically assigns pathway scores in the wrong
direction of the experimental perturbations (this may be due to increased
expression of negative feedback regulators that SPIA picks up due to the
underlying directed KEGG graph).

\subsection{Stability of Scores in Basal Expression}

What I have not shown yet is how stable the whole process is, i.e. much the
selection of input experiments influences the scores in basal expression. In
order to investigate this, I bootstrapped the experiment selection 1,000 times
and built models as described in section ***sub:Building-the-Model, using the
GDSC basal expression and yielding a 3-dimensional scores matrix with a score
for each cell line, pathway, and bootstrap. I regressed out either the effect
of the individual cell lines or the effect of the bootstraps, and quantified
the relative remaining variance in the scores:

$$ratio=\frac{var(cell\,lines\,|\,bootstraps)}{var(bootstraps\,|\,cell\,lines)}$$

The overview of those relative variances is shown in figure
fig:bootstraps-basal. Here, a value smaller than 1 indicates that the
experiment selection has a bigger effect than the cell line I apply the model
to (i.e., we can not observe a biological effect because it is hidden by the
noise of input experiments) and values bigger than 1 indicate the times the
biological context is more influential for providing the score than the input
selection (i.e, the biological context outweighs the exact selection of
perturbation input). For most pathways (TNFa, NFkB, MAPK, JAK-STAT, Hypoxia,
and EGFR) the variance of the input experiments as only a negligible influence
(smaller than 10\%) on the final scores. For p53, TGFb, and PI3K selection of
the input experiments still accounts for under 20\% of the observed variance of
basal pathway scores. For Trail and VEGF, it is about twice as large as the
variance of the input experiments. This can either point to the pathway not
being particularly well defined (if the experiments are also not well recovered
by the signature, like for VEGF in figure fig:ROC), or that the overall
number of input experiments is too small to guarantee a stable signature (like
for Trail, where the signature performs well but the overall number of
experiments are low, cf. figure fig:ROC).

%\begin{figure}[H]
%\centering
%\scalebox{.7}{
%<<stability, echo=FALSE, fig.width=5, fig.height=4.5>>=
%stab = import('../analyses/speed_bootstrap/stability_plot')
%stab$file2df('gdsc_matrix.RData') %>%
%    mutate(pathway = config$pathways(pathway, rev=TRUE)) %>%
%    stab$do_plot()
%@
%}
%\caption{Stability of scores when bootstrapping input experiments}
%\label{fig:stability}
%\end{figure}


\subsection{Correlation of Pathway Scores in Basal Expression}

As I am most interested in how basal signalling activity in cancer cell lines
and tumour samples correlates with outcomes such as drug response and survival,
one crucial point of deriving pathway response signatures is that they also
need to reflect pathway activation in basal gene expression. At this point, I
know that my perturbation-response signature genes correspond to the pathway
activation between a basal and perturbed condition, but not how well the
pattern of pathway activation from those perturbation experiments corresponds
to gene expression footprints of a constitutively active signalling pathway
leaves in basal gene expression.

Providing a definitive proof that the same signatures obtained correspond to
constitutive activation in basal expression is only possible using a range of
functional readouts (e.g. mutations activating pathways, drug response on
oncogene addiction) so I will defer this to chapter 4, where I investigate the
functional relevance of perturbation-response signatures compared to other
pathway methods.

What I can show, however, is how well known pathway cross-talk and structure
(as is known in literature and I have shown in figures
fig:Modelled-pathway-crosstalk and fig:sp2-exp-heatmap) translates to
pathway correlation in basal expression, and how well they agree between
tumours and cell lines. To this end, I computed pathway scores for all primary
tumours in the TCGA and cell lines in the GDSC (details section
sub:Correlation-in-basal), and checked how well they correlate.

I find that not only are the correlations in basal gene expression (figure
fig:Correlation-speed) similar to the ones in perturbed experiments (figures
fig:sp2-exp-heatmap and fig:circle-perturb), but they also correlate very
well with known cross-talk and do not change more than could be biologically
expected between primary tumours and cell lines. I find a high correlation
between EGFR and MAPK and a lesser one to PI3K, as well as TNFa and NFkB.
Another high correlation is between NFkB and JAK-STAT that I also observed in
perturbation experiments (figure fig:circle-perturb, but below cutoff of
$10^{-5}$ of figure fig:sp2-exp-heatmap).

At this point I found strong indications that the gene expression changes in
perturbation experiments can be described across many conditions using a linear
consensus signature whose score reflects pathway activation and this signature
is translatable to basal pathway activity in non-perturbed gene expression.

Using basal gene expression, we calculated the
Pearson correlation across all samples and tissues, and plotted the correlation
matrix between each pathway combination using the R package *corplot* for
GDSC and TCGA data separately.

Below are the correlation for TCGA primary tumour data (left) and GDSC cell lines (right) for
perturbation-response genes in basal expression. Sign indicated by colour of
the points (positive correlation blue, negative correlation red), strength by
colour shade and size of the point.

\begin{figure}[H]
\subfloat[Perturbation-response genes]{
<<cor_speed_matrix, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('speed_matrix')
@
}

\subfloat[Gene Ontology]{
<<cor_go, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('gsva_go')
@
}

\subfloat[Reactome]{
<<cor_reactome, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('gsva_reactome')
@
}

\subfloat[BioCarta]{
<<cor_speed_biocarta, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('gsva_biocarta')
@
}
\end{figure}
\begin{figure}[H]
\ContinuedFloat

\subfloat[SPIA]{
<<cor_spia, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('spia')
@
}

\subfloat[Pathifier]{
<<cor_pathifier, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('pathifier')
@
}

\subfloat[PARADIGM]{
<<cor_paradigm, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('paradigm')
@
}

\caption{Correlation of pathway scores in basal expression of the TCGA (left) and GDSC (right)}
\label{fig:cor}
\end{figure}
