\section{Pathway scores in Basal and Perturbed Condition}

<<setup1, include=FALSE>>=
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
st = import('stats')
plt = import('plot')
util = import('./util_1')
config = import('../config')
@

%\subsection{Size of the data set}

\begin{figure}[H]
<<dataset_size, echo=FALSE>>=
bars = import('../analyses/speed_overview/plot_bars')
bars$create_df() %>%
    mutate(variable = config$id2short(variable)) %>%
    bars$do_plot()
@
\caption{Comparison of dataset size between SPEED, Gatza2014, and ours}
\label{fig:dataset_size}
\end{figure}


%\subsection{Global Structure of perturbation experiments}
%
%\begin{figure}[H]
%<<global_structure, echo=FALSE, fig.width=10>>=
%import('../analyses/speed_raw/plot')$do_plot()
%@
%\caption{Clustering of fold changes (left) and top 100 genes (right)}
%\label{fig:clust}
%\end{figure}


%\subsection{Statistical significance of signature genes}

\begin{figure}[H]
<<sig_sign, echo=FALSE>>=
import('../analyses/speed_overview/model_significance')$plot()
@
\caption{Significance of the top 100 signature genes}
\label{fig:gene_significance}
\end{figure}


%\subsection{Gene sets used for different pathway methods}

%TODO: generate from config [need to fix list levels first]
%\begin{table}[H]
%\centering
%\caption{Pathway mapping for Gene Ontology}
%<<path_go, echo=FALSE>>=
%kable(roc$auc, digits=2, booktabs=TRUE)
%@
%\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for Gene Ontology}
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{Gene Ontology}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & GO:0007259 & ERBB signaling pathway\tabularnewline
Hypoxia & GO:0071456 & cellular response to hypoxia\tabularnewline
JAK-STAT & GO:0007259 & JAK-STAT signal transduction\tabularnewline
MAPK & GO:0000165 & MAPK cascade\tabularnewline
NFkB & GO:0038061 & NIK/NF-kappaB signaling\tabularnewline
p53 & GO:0030330 & DNA damage response, signal transduction by p53 class mediator\tabularnewline
PI3K & GO:0014065 & phosphatidylinositol 3-kinase signaling\tabularnewline
TNFa & GO:0033209 & tumor necrosis factor-mediated signaling pathway\tabularnewline
TGFb & GO:0007179 & transforming growth factor beta receptor signaling pathway\tabularnewline
Trail & GO:0036462 & TRAIL-activated apoptotic signaling pathway\tabularnewline
VEGF & GO:0038084 & vascular endothelial growth factor signaling pathway\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for Reactome and Pathifier}
\begin{tabular}{cc}
\hline
\multirow{1}{*}{Pathway} & Name\tabularnewline
\hline
\multirow{2}{*}{EGFR} & Signaling by EGFR\tabularnewline
 & Signaling by EGFR in Cancer\tabularnewline
Hypoxia & Cellular response to hypoxia\tabularnewline
\multirow{3}{*}{JAK-STAT} & Signaling by Interleukins\tabularnewline
 & Interferon Signaling\tabularnewline
 & Signalling to STAT3\tabularnewline
MAPK & Signalling to ERKs\tabularnewline
\multirow{2}{*}{NFkB} & TAK1 activates NFkB:w: by phosphorylation and activation of IKKs complex\tabularnewline
 & RIP-mediated NFkB activation via ZBP1\tabularnewline
p53 & Transcriptional Regulation by TP53\tabularnewline
\multirow{4}{*}{PI3K} & PI3K Cascade\tabularnewline
 & Constitutive Signaling by Aberrant PI3K in Cancer\tabularnewline
 & PI3K/AKT Signaling in Cancer\tabularnewline
 & PI3K/AKT activation\tabularnewline
TNFa & TNF signaling\tabularnewline
TGFb & Signaling by TGF-beta Receptor Complex\tabularnewline
Trail & TRAIL signaling\tabularnewline
VEGF & Signaling by VEGF\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for SPIA}
\begin{tabular}{ccc}
\hline
\multirow{2}{*}{Pathway} & \multicolumn{2}{c}{SPIA}\tabularnewline
\cline{2-3}
 & ID & Name\tabularnewline
\hline
EGFR & 04012 & ErbB signaling pathway\tabularnewline
Hypoxia & - & -\tabularnewline
JAK-STAT & 04630 & Jak-STAT signaling pathway\tabularnewline
MAPK & 04010 & MAPK signaling pathway\tabularnewline
NFkB & 04064 & NF-kappa B signaling pathway\tabularnewline
p53 & - & -\tabularnewline
PI3K & 04150 & mTOR signaling pathway\tabularnewline
TNFa & - & -\tabularnewline
TGFb & 04350 & TGF-beta signaling pathway\tabularnewline
Trail & 04210 & Apoptosis\tabularnewline
VEGF & 04370 & VEGF signaling pathway\tabularnewline
\hline
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Pathway mapping for PARADIGM}
\begin{tabular}{cc}
\hline
\multirow{2}{*}{Pathway} & \multirow{2}{*}{PARADIGM}\tabularnewline
 & \tabularnewline
\hline
EGFR & epidermal growth factor receptor activity (abstract)\tabularnewline
Hypoxia & response to hypoxia (abstract)\tabularnewline
JAK-STAT & STAT-1-3-5-active\tabularnewline
\multirow{1}{*}{MAPK} & MEK-1-2-active\tabularnewline
NFkB & NFkB Complex (complex)\tabularnewline
p53 & response to DNA damage stimulus (abstract)\tabularnewline
PI3K & PIK3CA\tabularnewline
TNFa & tumor necrosis factor receptor activity (abstract)\tabularnewline
TGFb & SMAD1-5-8-active\tabularnewline
Trail & induction of apoptosis (abstract)\tabularnewline
VEGF & platelet-derived growth factor receptor activity (abstract)\tabularnewline
\hline
\end{tabular}
\end{table}


\begin{figure}[H]
<<genesets, echo=FALSE, fig.width=19, fig.height=15>>=
import('../analyses/speed_overview/geneset_overlap')$venn()
@
\caption{Difference in gene sets between Perturbation-response genes and Gene Ontology/Reactome}
\label{fig:genesets}
\end{figure}

%\subsection{Pathway scores of different methods assigned to perturbations}


\begin{figure}[H]
\subfloat[Perturbation-response genes]{
<<perturb_speed, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('speed_matrix')
@
}

\subfloat[Gene Ontology]{
<<perturb_go, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('gsva_go')
@
}

\subfloat[Reactome]{
<<perturb_reactome, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('gsva_reactome')
@
}
\phantomcaption
\end{figure}
\begin{figure}[H]
\ContinuedFloat

\subfloat[BioCarta]{
<<perturb_biocarta, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('gsva_biocarta')
@
}

\subfloat[SPIA]{
<<perturb_spia, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('spia')
@
}

\subfloat[Pathifier]{
<<perturb_pathifier, echo=FALSE, fig.width=8, fig.height=3>>=
util$perturb_score_plots('pathifier')
@
}

%\subfloat[PARADIGM]{
%<<perturb_paradigm, echo=FALSE, fig.width=8, fig.height=3>>=
%util$perturb_score_plots('paradigm')
%@
%}
\caption{Pathway methods}
\label{fig:perturb_simple}
\end{figure}


%\begin{figure}[H]
%<<roc_curves, echo=FALSE>>=
%roc = import('../analyses/speed_raw/roc')
%roc$roc %>%
%    mutate(method = config$id2short(method)) %>%
%    roc$do_plot(width=1.05) +
%        config$facet_theme +
%        xlab("False positive rate (FPR)") +
%        ylab("True positive rate (FPR)")
%@
%\caption{ROC curves for different pathway methods}
%\label{fig:roc}
%\end{figure}

\begin{table}[H]
\centering
\caption{AUC under the ROC curve}
<<roc_auc, echo=FALSE>>=
roc = import('../analyses/speed_raw/roc')
kable(roc$auc, digits=2, booktabs=TRUE)
@
\end{table}

%\begin{figure}[H]
%\centering
%\scalebox{.7}{
%<<stability, echo=FALSE, fig.width=5, fig.height=4.5>>=
%stab = import('../analyses/speed_bootstrap/stability_plot')
%stab$file2df('gdsc_matrix.RData') %>%
%    mutate(pathway = config$pathways(pathway, rev=TRUE)) %>%
%    stab$do_plot()
%@
%}
%\caption{Stability of scores when bootstrapping input experiments}
%\label{fig:stability}
%\end{figure}

\begin{figure}[H]
\subfloat[Perturbation-response genes]{
<<cor_speed_matrix, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('speed_matrix')
@
}

\subfloat[Gene Ontology]{
<<cor_go, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('gsva_go')
@
}

\subfloat[Reactome]{
<<cor_reactome, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('gsva_reactome')
@
}

\subfloat[BioCarta]{
<<cor_speed_biocarta, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('gsva_biocarta')
@
}
\phantomcaption
\end{figure}
\begin{figure}[H]
\ContinuedFloat

\subfloat[SPIA]{
<<cor_spia, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('spia')
@
}

\subfloat[Pathifier]{
<<cor_pathifier, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('pathifier')
@
}

\subfloat[PARADIGM]{
<<cor_paradigm, echo=FALSE, fig.height=3, fig.width=8>>=
util$cor_plots('paradigm')
@
}

\caption{Correlation of pathway scores in basal expression of the TCGA (left) and GDSC (right)}
\label{fig:cor}
\end{figure}
