---
title: "Pan-cancer improvements with mutations and MAPK scores"
author: "Michael Schubert (schubert@ebi.ac.uk)"
---

```{r code, include=FALSE}
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
st = import('stats')
df = import('data_frame')
plt = import('plot')
gdsc = import('data/gdsc')
util = import('./util_3')
followup = import('../analyses/drug_assocs_followup/util')

tissues = gdsc$tissues()
Ys = gdsc$drug_response('IC50s')
scores = io$load("../scores/gdsc/pathways_mapped/speed_matrix.RData")
mut = gdsc$mutated_genes(intogen=TRUE)
ar$intersect(tissues, Ys, scores, mut, along=1)

nst = function(x) names(x[x])

# prepare stratifications of MAPK pathway
drug = "Trametinib" # "(5Z)-7-Oxozeaenol", "RDEA119"

mapk = scores[names(tissues), "MAPK"]
has_mut = mut[,"BRAF"] | mut[,"KRAS"] | mut[,"NRAS"]
path_active = mapk > quantile(mapk)[4] # top 25%
path_inactive = mapk < quantile(mapk)[2] # bottom 25%
path_null = mapk > quantile(mapk)[2] & mapk < quantile(mapk)[4] # rest

pancan = list(
    # stratification by mutation
    "MAPK_all" = nst(!is.na(mapk)),
    "MAPK_wt" = nst(!has_mut),
    "MAPK_mut" = nst(has_mut),

    # stratification by SPEED score
    "MAPK+" = nst(path_active),
    "MAPK-" = nst(path_inactive),
    "MAPK_null" = nst(path_null),

    # stratification by SPEED score, wild-type subset
    "MAPK_wt" = nst(!has_mut),
    "MAPK+_wt" = nst(!has_mut & (path_active | path_null)),
    "MAPK-_wt" = nst(!has_mut & path_inactive),

    # stratification by SPEED score, mutated subset
    "MAPK_mut" = nst(has_mut),
    "MAPK+_mut" = nst(has_mut & path_active),
    "MAPK-_mut" = nst(has_mut & (path_inactive | path_null))
)
```

# Volcano Plots

## SPEED

```{r volcano_speed_matrix, echo=FALSE}
util$volcano("speed_matrix")
```

## GO

```{r volcano_go, echo=FALSE}
util$volcano("gsea_go")
```

## Reactome

```{r volcano_reactome, echo=FALSE}
util$volcano("gsea_reactome")
```

## BioCarta

```{r volcano_biocarta, echo=FALSE}
util$volcano("gsea_biocarta")
```

## SPIA

```{r volcano_spia, echo=FALSE}
util$volcano("spia")
```

## Pathifier

```{r volcano_pathifier, echo=FALSE}
#util$volcano("pathifier") #FIXME: not there yet, why?
```

## PARADIGM

```{r volcano_paradigm, echo=FALSE}
util$volcano("paradigm")
```

# Trametinib + MAPK

## Overview

```{r tram1, echo=FALSE}
followup$drug_range_box(drug, stratify=list(Pancan=pancan))
```

## Stratification by mutation alone

```{r tram2_2, echo=FALSE}
followup$drug_range_box(drug, stratify=list(Pancan=pancan[1:3]))
```

## Stratification by pathway score alone

```{r tram3_2, echo=FALSE}
followup$drug_range_box(drug, stratify=list(Pancan=pancan[4:6]))
```

## Stratification of wild-type sub-population

```{r tram4, echo=FALSE}
followup$drug_range_box(drug, stratify=list(Pancan=pancan[7:9]))
```

## Stratification of mutated sub-population

```{r tram5, echo=FALSE}
followup$drug_range_box(drug, stratify=list(Pancan=pancan[10:12]))
```

# Nutlin-3a + p53

```{r p53, echo=FALSE}
p53 = scores[names(tissues), "p53"]
stratify = list(Pancan = list(
    "p53+" = nst(p53 > quantile(p53)[4]), # top 25%
    "p53-" = nst(p53 < quantile(p53)[2]), # bottom 25%
    "p53_null" = nst(p53 > quantile(p53)[2] & p53 < quantile(p53)[4]), # bottom 25%
    "TP53_wt" = nst(!mut[,"TP53"]),
    "TP53_mut" = nst(mut[,"TP53"]),
    "TP53+_mut" = nst(mut[,"TP53"] & p53 > quantile(p53)[3]),
    "TP53-_mut" = nst(mut[,"TP53"] & p53 < quantile(p53)[3])
))

followup$drug_range_box("Nutlin-3a", stratify=stratify)
```
