\section{Drug response in the GDSC panel}

<<setup3, include=FALSE>>=
library(dplyr)
b = import('base')
io = import('io')
ar = import('array')
st = import('stats')
df = import('data_frame')
plt = import('plot')
gdsc = import('data/gdsc')
util = import('./util_3')
config = import('../config')

assocs = b$lnapply(config$methods$analysis_set, util$vp$load_fun)
@

\subsection{Pan-cancer associations}

\begin{figure}[H]
<<drug_volcano_pancan, echo=FALSE, fig.width=8, fig.height=12>>=
p = assocs %>%
    b$lnapply(function(x) x$assocs.pan) %>%
    df$add_name_col(col="method", bind=TRUE) %>%
    mutate(label = paste(drug, scores, sep=":"),
           method = config$id2short(method)) %>%
    plt$color$p_effect(pvalue="adj.p", effect="estimate", thresh=0.05, dir=-1) %>%
    plt$volcano(base.size=0.1, text.size=2, p=0.05) +
        facet_wrap(~method, ncol=2, scales="free_x") +
        config$facet_theme
plt$symmetrise_scale(p)
@
\caption{}
\label{fig:drug-volcano-pancan}
\end{figure}


\subsection{Tissue-specific associations}

\begin{figure}[H]
<<drug_volcano_tissue, echo=FALSE, fig.width=8, fig.height=12>>=
p = assocs %>%
    b$lnapply(function(x) x$assocs.tissue) %>%
    df$add_name_col(col="method", bind=TRUE) %>%
    filter(subset == "clinical") %>%
    mutate(label = paste(drug, scores, tissue, sep=":"),
           method = config$id2short(method)) %>%
    plt$color$p_effect(pvalue="adj.p", effect="estimate", thresh=0.1, dir=-1) %>%
    plt$volcano(base.size=1, text.size=2, p=0.1) +
        facet_wrap(~method, ncol=2, scales="free_x") +
        config$facet_theme
plt$symmetrise_scale(p)
@
\caption{}
\label{fig:drug-volcano-tissue}
\end{figure}
