<<sig_val_setup, include=FALSE>>=
do = import('../analyses/signature_validation/do')
@

\begin{figure}[H]
<<sig_val, echo=FALSE, fig.width=12, fig.height=12>>=
do$p + theme(strip.text.x = element_text(size = 10))
@
\caption{Relative pathway activation patterns for activity measurement vs.
inference by PROGENy. Data sources (publication DOI in panel title) are experiments where PTMs (mostly Western
Blots of pathway drivers) and gene expression were measured in at least
duplicate and that were not previously included in model building. Each panel
shows a pathway with activity measurement on the left and inferred pathway
score on the right. The Y-axis is scaled to a normal distribution and  should
be used only to compare basal vs. perturbed experiments of the same kind.
Difference quantified using a one-tailed t-test.
}
\label{fig:sig-val}
\end{figure}
