\documentclass{article}

\input{config}

\title{Supplementary Material}
\author{Michael Schubert (schubert@ebi.ac.uk)}

\begin{document}

\maketitle

\tableofcontents

\Sexpr{knit_child('S1_Pathway_Scores.Rnw')}

\Sexpr{knit_child('S2_TCGA-Driver+Pathway.Rnw')}

\Sexpr{knit_child('S3_GDSC-Pancan.Rnw')}

\Sexpr{knit_child('S4_GDSC-Tissue+Stratification.Rnw')}

\Sexpr{knit_child('S5_Survival.Rnw')}

\end{document}
