```{r prepare, include=FALSE}
library(pheatmap)
library(dplyr)
io = import('io')
ar = import('array')
plt = import('plot')

vars = io$load(module_file('gene_variants.RData'))$variants

#' @param TP  current study where gene is mutated
#' @param FN  current study where gene is not mutated
#' @param FP  other studies where gene is mutated
#' @param TN  other studies where gene is not mutated
FET = function(TP, FN, FP, TN) {
    ff = function(tp, fn, fp, tn) fisher.test(matrix(c(tp, fn, tn, fp), nrow=2))
    re = mapply(ff, TP, FN, FP, TN, SIMPLIFY=FALSE, USE.NAMES=FALSE)

    list(p.value = sapply(re, function(x) x$p.value, USE.NAMES=FALSE),
         odds.ratio = unname(sapply(re, function(x) x$estimate, USE.NAMES=FALSE)))
}
```

# Mutated gene enrichment

Test for enrichment of mutated genes of a certain cancer type
compared to other cancer types.

```{r freq_genes, echo=FALSE}
genes = vars %>%
    select(id, study, hgnc, n_gene, n_gene_per_study) %>%
    mutate(n = n_distinct(id)) %>%
    group_by(study) %>%
    mutate(n_study = n_distinct(id)) %>%
    ungroup() %>%
    select(-id) %>%
    distinct() %>%
    do(mutate(., estimate = FET(n_gene_per_study, n_study - n_gene_per_study,
                                n - n_gene, n_gene - n_gene_per_study)$odds.ratio)) %>%
    do(mutate(., p.value = FET(n_gene_per_study, n_study - n_gene_per_study,
                               n - n_gene, n_gene - n_gene_per_study)$p.value)) %>%
    select(-n) %>%
    mutate(adj.p = p.adjust(p.value, method="fdr")) %>%
    arrange(adj.p)

head(as.data.frame(genes), 50)

```

# Variant enrichment

Test for enrichment of variant frequency in one cancer type
compared to others.

```{r freq_vars, echo=FALSE}
gvars = vars %>%
    select(id, study, label, n_var, n_var_per_study) %>%
    mutate(n = n_distinct(id)) %>%
    group_by(study) %>%
    mutate(n_study = n_distinct(id)) %>%
    ungroup() %>%
    select(-id) %>%
    distinct() %>%
    do(mutate(., estimate = FET(n_var_per_study, n_study - n_var_per_study,
                                n - n_var, n_var - n_var_per_study)$odds.ratio)) %>%
    do(mutate(., p.value = FET(n_var_per_study, n_study - n_var_per_study,
                               n - n_var, n_var - n_var_per_study)$p.value)) %>%
    select(-n) %>%
    filter(label != "other") %>%
    mutate(adj.p = p.adjust(p.value, method="fdr")) %>%
    arrange(adj.p)

head(as.data.frame(gvars), 50)
```
